<?php
/**
 * Additional Fields
 */
add_filter( 'rwmb_meta_boxes', 'your_prefix_function_name' );

function your_prefix_function_name( $meta_boxes ) {
    $prefix = '';

    $meta_boxes[] = [
        'title'          => __( 'Home', 'your-text-domain' ),
        'post_types'     => ['page'],
        'closed'         => false,
        'default_hidden' => false,
        'autosave'       => false,
        'revision'       => false,
        'include'        => [
            'relation' => 'OR',
            'ID'       => [73],
        ],
        'tabs'           => [
            'tab_mkbfdswl9l'  => [
                'label' => 'Home',
                'icon'  => '',
            ],
            'tab_azkl4tlm26u' => [
                'label' => 'Grid',
                'icon'  => '',
            ],
            'tab_3' => [
                'label' => 'Subscribe',
                'icon'  => '',
            ],
        ],
        'fields'         => [
            [
                'name'              => __( 'Header', 'your-text-domain' ),
                'id'                => $prefix . 'header',
                'type'              => 'group',
                'collapsible'       => false,
                'clone'             => false,
                'clone_empty_start' => false,
                'hide_from_rest'    => false,
                'hide_from_front'   => false,
                'tab'               => 'tab_mkbfdswl9l',
                'fields'            => [
                    [
                        'name'              => __( 'Title', 'your-text-domain' ),
                        'id'                => $prefix . 'text_uqeycw0cd5d',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Content', 'your-text-domain' ),
                        'id'                => $prefix . 'content',
                        'type'              => 'wysiwyg',
                        'raw'               => false,
                        'required'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Button_Text', 'your-text-domain' ),
                        'id'                => $prefix . 'button_text',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Button_URL', 'your-text-domain' ),
                        'id'                => $prefix . 'button_url',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Single Image', 'your-text-domain' ),
                        'id'                => $prefix . 'single_image_zxtzdoxryqn',
                        'type'              => 'single_image',
                        'force_delete'      => false,
                        'required'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                    ],
                ],
            ],
            [
                        'name'              => __( 'Grid', 'your-text-domain' ),
                        'id'                => $prefix . 'group_6dtvh7ymzoy',
                        'type'              => 'group',
                        'collapsible'       => false,
                        'clone'             => true,
                        'sort_clone'        => false,
                        'clone_default'     => false,
                        'clone_as_multiple' => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'tab'               => 'tab_azkl4tlm26u',
                        'fields'            => [
                            [
                                'name'              => __( 'Title', 'your-text-domain' ),
                                'id'                => $prefix . 'title',
                                'type'              => 'text',
                                'required'          => false,
                                'disabled'          => false,
                                'readonly'          => false,
                                'clone'             => false,
                                'clone_empty_start' => false,
                                'hide_from_rest'    => false,
                                'hide_from_front'   => false,
                                'limit_type'        => 'character',
                            ],
                            [
                                'name'              => __( 'Content', 'your-text-domain' ),
                                'id'                => $prefix . 'content',
                                'type'              => 'wysiwyg',
                                'raw'               => false,
                                'required'          => false,
                                'clone'             => false,
                                'clone_empty_start' => false,
                                'hide_from_rest'    => false,
                                'hide_from_front'   => false,
                                'limit_type'        => 'character',
                            ],
                            [
                                'name'              => __( 'Link', 'your-text-domain' ),
                                'id'                => $prefix . 'link',
                                'type'              => 'text',
                                'required'          => false,
                                'disabled'          => false,
                                'readonly'          => false,
                                'clone'             => false,
                                'clone_empty_start' => false,
                                'hide_from_rest'    => false,
                                'hide_from_front'   => false,
                                'limit_type'        => 'character',
                            ],
                            [
                                'name'              => __( 'feature image', 'your-text-domain' ),
                                'id'                => $prefix . 'feature_image',
                                'type'              => 'single_image',
                                'force_delete'      => false,
                                'required'          => false,
                                'clone'             => false,
                                'clone_empty_start' => false,
                                'hide_from_rest'    => false,
                                'hide_from_front'   => false,
                            ],
                        ],
                
            ],   [
                'name'              => __( 'Subscribe', 'your-text-domain' ),
                'id'                => $prefix . 'subscribe',
                'type'              => 'group',
                'collapsible'       => false,
                'clone'             => false,
                'clone_empty_start' => false,
                'hide_from_rest'    => false,
                'hide_from_front'   => false,
                'tab'               => 'tab_3',
                'fields'            => [
                    [
                        'name'              => __( 'Title', 'your-text-domain' ),
                        'id'                => $prefix . 'title',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Content', 'your-text-domain' ),
                        'id'                => $prefix . 'content',
                        'type'              => 'wysiwyg',
                        'raw'               => false,
                        'required'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Button_Text', 'your-text-domain' ),
                        'id'                => $prefix . 'button_text',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Button_URL', 'your-text-domain' ),
                        'id'                => $prefix . 'button_url',
                        'type'              => 'text',
                        'required'          => false,
                        'disabled'          => false,
                        'readonly'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                        'limit_type'        => 'character',
                    ],
                    [
                        'name'              => __( 'Single Image', 'your-text-domain' ),
                        'id'                => $prefix . 'single_image',
                        'type'              => 'single_image',
                        'force_delete'      => false,
                        'required'          => false,
                        'clone'             => false,
                        'clone_empty_start' => false,
                        'hide_from_rest'    => false,
                        'hide_from_front'   => false,
                    ],
                ],
            ],
        ],
    ];

    return $meta_boxes;
}